contentmanager/urls.py
from django.conf.urls import url
from contentmanager.views import Index, UrlList, LinkCreateView, LinkEditView, LinkDeleteView

app_name = "contentmanager"
urlpatterns = [
    url(r'^$', Index.as_view(), name="index"),
    url(r'^urllist/$', UrlList.as_view(), name="urllist"),
    url(r'^create/$', LinkCreateView.as_view(), name="link_create"),
    url(r'^update/(?P<url_pk>\d+)/$', LinkEditView.as_view(), name="link_update"),
    url(r'^delete/(?P<url_pk>\d+)/$', LinkDeleteView.as_view(), name="link_delete")


]

kiosk/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^contentmanager/', include('contentmanager.urls', namespace='contentmanager')),
    url(r'^terminal/', include('terminal.urls', namespace='terminal')),
    url(r'^', include('login.urls', namespace='login')),
    url(r'^admin/', admin.site.urls),
]

login/urls.py
from django.conf.urls import url
from login.views import Index

app_name='login'
urlpatterns = [
    url(r'^$', Index.as_view(), name='user_login'),
]

terminal/urls.py
from django.conf.urls import url
from terminal.views import Index, Welcome

app_name = "terminal"
urlpatterns = [
    url(r'^$', Index.as_view(), name="index"),
    url(r'^welcome/$', Welcome.as_view(), name="welcome")

]

contentmanager/models.py
from django.db import models
from django.utils import timezone

class links(models.Model):
    name = models.CharField('name', max_length=255, blank=False)
    url = models.URLField('url', max_length=255, blank=False)
    created = models.DateTimeField('created',default=timezone.now())

terminal/models.py
from django.db import models

# Create your models here.

contentmanager/forms.py
from django.forms import ModelForm
from .models import links
from django.utils.timezone import datetime
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, ButtonHolder, Submit, HTML
from crispy_forms.bootstrap import FormActions


class add_link(ModelForm):
    class Meta:
        model = links
        fields = ['name', 'url']

contentmanager/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from fm.views import AjaxCreateView, AjaxUpdateView, AjaxDeleteView
from django.views.generic import ListView, CreateView
from django.http import HttpResponseRedirect
from django.views import View
from .models import links
from .forms import add_link

class Index(View):
    def get(self, request):
        return redirect("contentmanager:urllist")

class UrlList(ListView):
    model = links
    template_name = 'url_list.html'

class LinkCreateView(AjaxCreateView):
    form_class = add_link

class LinkEditView(AjaxUpdateView):
    form_class = add_link
    model = links
    pk_url_kwarg = 'url_pk'

class LinkDeleteView(AjaxDeleteView):
     model = links
     pk_url_kwarg = 'url_pk'

login/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.views import View

from login.Authenicate.authenticate import Authenticate
from .loginform import LoginForm

class Index(View):
    def get(self, request):
        success = True
        form = LoginForm()
        context = {'form': form, 'success': success}
        return render(request, 'login.html', context)


    def post(self, request):
        form = LoginForm()
        userId = request.POST['user_name']
        password = request.POST['password']
        if password != "kio$k":
            authenticated = Authenticate.auth(userId, password)
        else:
           return redirect('terminal:index')
        if not authenticated:
            success = False
            context = {'form': form, 'success': success}
            request.session['loggedIn'] = False
            return redirect('terminal:index')
        else:
            request.session['loggedIn'] = True
            request.session['UserData'] = authenticated
            return redirect('contentmanager:index')

terminal/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View
from contentmanager.models import links
from django.views.generic import ListView

class Index(View):
    def get(self, request):
        linkList = links.objects.all()
        dataContext = {'object_list': linkList}
        return render(request, 'index.html', dataContext)


class Welcome(View):
    def get(self, request):
        return render(request, 'welcome.html')

contentmanager/templates/index.html
{% extends '_layout.html' %}
{% block content %}

    <h1>I'm here folks!!</h1>

{% endblock %}

contentmanager/templates/url_instance.html
<div class="object" id="object-{{ object.pk }}"

contentmanager/templates/url_list.html
{% extends '_layout.html' %}
{% block content %}
    <h2>Url List</h2>
    <div id="inner">
    <a href="{% url 'contentmanager:link_create' %}" class="fm-create" data-fm-head="Create" data-fm-callback="reload">Add Link</a>
        {% for url in object_list %}
            <ul class="urlList list-inline">
                <li class="urlListItem "><h3>{{ url.name }}</h3></li>
                <li class="urlListItem "><h3>{{ url.url }}</h3></li>
                <li class="urlListItem ">
                    <h3>
                        <a href="{% url 'contentmanager:link_update' url_pk=url.id %}"
                           class="fm-update" data-fm-head="Update"
                           data-fm-callback="reload">Update</a>
                    </h3>
                </li>
                 <li class="urlListItem ">
                     <h3>
                        <a href="{% url 'contentmanager:link_delete' url_pk=url.id %}"
                           class="fm-delete" data-fm-head="Delete"
                           data-fm-callback="reload">Delete</a>
                     </h3>
                </li>
            </ul>
        {% endfor %}
    </div>
{% endblock %}

templates/_layout.html
{% load staticfiles %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <Title>{% block title %}{% endblock %}</Title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" type="image/png" href="{% static 'img/header.png' %}" />
        <link rel="stylesheet" href="{% static 'css/vendor/bootstrap.min.css' %}">
        <style>
            body {
                padding-top: 50px;
                padding-bottom: 20px;
            }
        </style>
        <link rel="stylesheet" href="{% static 'jquery-ui-1.12.1.custom/jquery-ui.min.css' %}"/>
        <link rel="stylesheet" href="{% static 'jquery-ui-1.12.1.custom/jquery-ui.theme.min.css' %}"/>
        <link rel="stylesheet" href="{% static 'css/vendor/bootstrap-theme.min.css' %}" />
        <link rel="stylesheet" href="{% static 'css/vendor/jquery.timepicker.css' %}" />
        <link rel="stylesheet" href="{% static 'css/main.css' %}" />
        <script src="{% static 'jquery-ui-1.12.1.custom/external/jquery/jquery.js' %}"></script>
        <script src="{% static 'jquery-ui-1.12.1.custom/jquery-ui.min.js' %}"></script>
        <script src="{% static 'js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>
        <script src="{% static 'endless_pagination/js/endless-pagination.js' %}"></script>


    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div id="wrapper" class="navbar-header">
            <div id="navbarImgDiv">
                <a class="navbar-brand" href="#"><img id="headerImg" src="{% static 'img/header.png' %}"></a>
            </div>
            <div id="navbarHeadLine">
                <h2></h2>
            </div>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
        </div><!--/.navbar-collapse -->
      </div>
    </nav>
    <div id="mainContainer" class="container">
      <div class="row">
         <div id="headerDiv">{% block header %}{% endblock %}</div>
      </div>
      <div class="row">
          <div id="contentDiv" class="col-md-12">{% block content %}{% endblock %}</div>
      </div>
      <hr>
      {% include "fm/modal.html" %}
      <script type="text/javascript">
          $(function () {
              $.fm({debug:true})
          });
      </script>
      <footer>
        <p>&copy; Martin Transportation Systems 2017</p>
      </footer>
    </div> <!-- /container -->
        <script>window.jQuery || document.write('<script src="{% static 'js/vendor/jquery-1.11.2.min.js' %}"><\/script>')</script>
        <script src="{% static 'js/vendor/bootstrap.js' %}"></script>
        <script src="{% static 'js/plugins.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>

terminal/templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Main Kiosk Page</title>
    <link rel="stylesheet" href="{% static 'jquery-ui-1.12.1.custom/jquery-ui.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'jquery-ui-1.12.1.custom/jquery-ui.theme.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/vendor/bootstrap-theme.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/normalized.css' %}" />
    <link rel="stylesheet" href="{% static 'css/kioskmain.css' %}"/>
    <script src="{% static 'jquery-ui-1.12.1.custom/external/jquery/jquery.js' %}"></script>
    <script src="{% static 'jquery-ui-1.12.1.custom/jquery-ui.min.js' %}"></script>
    <script src="{% static 'js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>
    <script src="{% static 'endless_pagination/js/endless-pagination.js' %}"></script>
</head>
<body>
<div class="container">
    <div class="first">
        <div id="innerFirst">
            <img class="img-responsive" src="{% static 'img/header.png' %}">
        </div>
    </div>
    <div class="third">
        <div class="container-fluid">
            <iframe id="maindisplay" src="{% url 'terminal:welcome' %}"></iframe>
        </div>
    </div>
    <div class="second">
        {% include 'terminal_list.html' %}
    </div>
</div>
</body>
</html>

terminal/templates/terminal_list.html
{% load staticfiles %}
<div class="container">
    {% for link in object_list %}
        <div class="linkBox col-md-12">
            <p><span class="linkList">{{ link.name }}</span></p>
        </div>
    {% endfor %}
</div>

terminal/templates/welcome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome to Kiosk</title>
</head>
<body>
<div class="container-fluid">
    <div class="col-sm-12" id="welcomeContainer">
        <h1 class="h1">
            Welcome to MTS Kiosk
        </h1>
        <h4 class="h4">
            Please Make a selection
        </h4>
    </div>
</div>
</body>
</html>